name: CI Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2 — Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 — Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4 — Build & Push Backend Image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./ETbackend
          file: ./ETbackend/backend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ansible-final-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ansible-final-backend:${{ github.sha }}

      # Step 5 — Build & Push Frontend Image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/frontend.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ansible-final-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/ansible-final-frontend:${{ github.sha }}